CREATE TABLE chat
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_chat PRIMARY KEY (id)
);

ALTER TABLE chat
    ADD CONSTRAINT FK_CHAT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);