CREATE TABLE message
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    send_at TIMESTAMP WITHOUT TIME ZONE,
    content VARCHAR(255),
    message_type VARCHAR(255),
    is_user BOOLEAN                                 NOT NULL,
    chat_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);