server:
  port: 8080

spring:
  application:
    name: "aischemabuilder"

  profiles:
    active: prod

  config:
    import: "config/db-${spring.profiles.active}.yml"

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web: DEBUG

llm:
  api-url: https://api.deepseek.com/chat/completions
  model: deepseek-chat
  token: sk-e46b5fda16bd40d8934ce29ff0f2e7c1